### PR TITLE
ratna: annotation results from first half of zhihan data

### PR DESCRIPTION
**Pull request by ratnadiraw**
I moved the 18 remaining codes that I didn't work on to the data/removed directory. Thank you.

### CODE REVIEW

**Comment by terryyz** [comment]
It seems that your `script/run.sh` isn't correctly set up, and therefore, no test has been run. You need to initialize `NAMES` to properly run over the corresponding split.

**Comment by ratnadiraw** [comment]
Hi @terryyz, if I put NAMES, then the other "zhihan" would also be run which can fail the tests. I have mentioned in the chat that I can run the test correctly in my repo:
image

The change on the run.sh also only to make sure that it ran the code that I have modified.
image

**Comment by imamnurby** [comment]
Hi @ratnadiraw , may I know at which step this is failing? Is it when executing parse.py?
Previously I tried to change this line https://github.com/bigcode-project/open-eval/blob/c3b0fc9fe8e46a8d8cef78c26f92b121b778cb22/script/parse.py#L470 to only include zhihan data.

Here is my fork https://github.com/imamnurby/open-eval/blob/cb94d6b39b45ba81d3d47ca8fe771f192a015ad2/script/parse.py#L470.

It will only parse my split, ignoring the others.

**Comment by ratnadiraw** [comment]
There is no step that fails, it just does not run here.
image

It can run just fine on my repo:
image

**Comment by ratnadiraw** [comment]
I have updated the parse.py and run.sh (+f_935, f951, 961) so it can pass the test in the workflow. Thank you!

**Pull request merged**
